<?php
require 'auth.php';require_login();require 'db.php';require 'layout.php';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(isset($_POST['take_case']) && $_SESSION['role']==='volunteer'){$rid=(int)$_POST['take_case'];$uid=$_SESSION['user_id'];$s=$conn->prepare("UPDATE reports SET handled_by=?,status='in_progress' WHERE report_id=? AND handled_by IS NULL");$s->bind_param('ii',$uid,$rid);$s->execute();$conn->query("UPDATE volunteer_stats SET number_of_cases_handled=number_of_cases_handled+1 WHERE user_id=".(int)$uid);header('Location: reports.php?msg='.urlencode('Case assigned to you.'));exit;}
 if(isset($_POST['close_case']) && $_SESSION['role']==='volunteer'){$rid=(int)$_POST['close_case'];$uid=$_SESSION['user_id'];$s=$conn->prepare("UPDATE reports SET status='closed' WHERE report_id=? AND handled_by=?");$s->bind_param('ii',$rid,$uid);$s->execute();header('Location: reports.php?msg='.urlencode('Case closed.'));exit;}
 $type=trim($_POST['report_type']??'');$desc=trim($_POST['description']??'');$loc=trim($_POST['location']??'');$animal=(int)($_POST['animal_id']??0);$animal=$animal?:null;$uid=$_SESSION['user_id'];$s=$conn->prepare('INSERT INTO reports(reported_by,animal_id,report_type,description,location) VALUES(?,?,?,?,?)');$s->bind_param('iisss',$uid,$animal,$type,$desc,$loc);$s->execute();header('Location: reports.php?msg='.urlencode('Report submitted.'));exit;
}
$reports=$conn->query('SELECT r.*,a.name animal_name,u.full_name reporter,v.full_name handler FROM reports r LEFT JOIN animal a ON r.animal_id=a.animal_id JOIN users u ON r.reported_by=u.user_id LEFT JOIN users v ON r.handled_by=v.user_id ORDER BY r.report_id DESC');$animals=$conn->query('SELECT animal_id,name FROM animal ORDER BY name');page_top('Reports');
?><div class="section-head"><h1 class="page-title">Rescue Reports</h1></div><form class="form-card form-grid" method="post"><select name="report_type" required><option value="">Report type</option><option>Injured animal</option><option>Stray animal</option><option>Lost animal</option><option>Abuse concern</option><option>Other</option></select><select name="animal_id"><option value="">No existing animal</option><?php while($a=$animals->fetch_assoc()):?><option value="<?=$a['animal_id']?>" <?=((int)($_GET['animal_id']??0)==$a['animal_id'])?'selected':''?>><?=h($a['name'])?></option><?php endwhile;?></select><input class="full" name="location" placeholder="Location" required><textarea class="full" name="description" rows="4" placeholder="Describe the situation" required></textarea><button class="btn full">Submit report</button></form><div class="section-head"><h2>All reports</h2></div><div class="table-wrap"><table><tr><th>ID</th><th>Type</th><th>Animal</th><th>Reporter</th><th>Handler</th><th>Status</th><th>Location</th><th>Action</th></tr><?php while($r=$reports->fetch_assoc()):?><tr><td>#<?=$r['report_id']?></td><td><?=h($r['report_type'])?></td><td><?=h($r['animal_name']??'—')?></td><td><?=h($r['reporter'])?></td><td><?=h($r['handler']??'Unassigned')?></td><td><span class="tag"><?=h($r['status'])?></span></td><td><?=h($r['location'])?></td><td><?php if($_SESSION['role']==='volunteer'&&!$r['handled_by']):?><form method="post"><button class="btn small" name="take_case" value="<?=$r['report_id']?>">Take case</button></form><?php elseif($_SESSION['role']==='volunteer'&&$r['handled_by']==$_SESSION['user_id']&&$r['status']!=='closed'):?><form method="post"><button class="btn small secondary" name="close_case" value="<?=$r['report_id']?>">Close</button></form><?php else:?>—<?php endif;?></td></tr><?php endwhile;?></table></div><?php page_bottom(); ?>
